name: PR Check

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress
        run: npm run docs:build

      - name: Verify build
        run: |
          if [ -d "docs/.vitepress/dist" ] && [ -f "docs/.vitepress/dist/index.html" ]; then
            echo "✅ Build successful!"
          else
            echo "❌ Build failed!"
            exit 1
          fi
